#!/bin/bash
# Complete GPU fix procedure

echo "=========================================="
echo "GPU Fix Procedure"
echo "=========================================="
echo ""
echo "The CUDA driver test shows cuInit() failing (error 999)."
echo "This is a driver state issue that usually requires a reboot."
echo ""
echo "STEP 1: Add user to video/render groups"
echo "----------------------------------------"
USER=$(whoami)
echo "Run these commands (requires sudo):"
echo "  sudo usermod -a -G video $USER"
echo "  sudo usermod -a -G render $USER"
echo ""
echo "STEP 2: Reboot System"
echo "----------------------------------------"
echo "This is CRITICAL - reboot clears CUDA driver state:"
echo "  sudo reboot"
echo ""
echo "STEP 3: After Reboot - Reinstall PyTorch with CUDA"
echo "----------------------------------------"
echo "cd /home/wiseguy/dev"
echo "source venv/bin/activate"
echo "pip uninstall torch torchvision torchaudio -y"
echo "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
echo ""
echo "STEP 4: Test"
echo "----------------------------------------"
echo "python3 -c \"import torch; print('CUDA:', torch.cuda.is_available()); print('GPU:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A')\""
echo ""
echo "=========================================="
echo "Why Reboot is Needed"
echo "=========================================="
echo "The CUDA driver state is stuck. Error 999 from cuInit() means"
echo "the driver can't initialize properly. A reboot:"
echo "1. Clears driver state"
echo "2. Reinitializes CUDA driver"
echo "3. Fixes permission/access issues"
echo ""
echo "This is the most common fix for 'CUDA unknown error'."


